# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe359ce0cfbdaed9b3b3eebe25e47e1c8760e825c79ee90604af1e026dbb038b019b39f8a6984dea029dfa8639620ea756aabbc0c2a31ef19613c3c5d286077

test:
  secret_key_base: d9e7ae0071f05276ca3e38a07903e91b882b4a35e284b42575c3e87bcb5cdc92b89bf543811b779292bbb95ff70757616e5b722bbc7752d20de1d35f10db909a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
